/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSplatRouteImport } from './routes/app.$'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppCurrentAffairsRouteImport } from './routes/app.current-affairs'
import { Route as AppReviewRouteImport } from './routes/app.review'
import { Route as DevMathRouteImport } from './routes/dev.math'
import { Route as ApiVoiceTranscribeRouteImport } from './routes/api/voice/transcribe'
import { Route as AppMockTestTestIdRouteImport } from './routes/app.mock-test.$testId'
import { Route as AppMockTestsIndexRouteImport } from './routes/app.mock-tests.index'
import { Route as AppResultsIndexRouteImport } from './routes/app.results.index'
import { Route as AppResultsAttemptIdRouteImport } from './routes/app.results.$attemptId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCurrentAffairsRoute = AppCurrentAffairsRouteImport.update({
  id: '/current-affairs',
  path: '/current-affairs',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const DevMathRoute = DevMathRouteImport.update({
  id: '/dev/math',
  path: '/dev/math',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTranscribeRoute = ApiVoiceTranscribeRouteImport.update({
  id: '/api/voice/transcribe',
  path: '/api/voice/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMockTestTestIdRoute = AppMockTestTestIdRouteImport.update({
  id: '/mock-test/$testId',
  path: '/mock-test/$testId',
  getParentRoute: () => AppRoute,
} as any)
const AppMockTestsIndexRoute = AppMockTestsIndexRouteImport.update({
  id: '/mock-tests/',
  path: '/mock-tests/',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsIndexRoute = AppResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsAttemptIdRoute = AppResultsAttemptIdRouteImport.update({
  id: '/results/$attemptId',
  path: '/results/$attemptId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$': typeof AppSplatRoute
  '/app/admin': typeof AppAdminRoute
  '/app/current-affairs': typeof AppCurrentAffairsRoute
  '/app/review': typeof AppReviewRoute
  '/dev/math': typeof DevMathRoute
  '/app/': typeof AppIndexRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/app/mock-test/$testId': typeof AppMockTestTestIdRoute
  '/app/results/$attemptId': typeof AppResultsAttemptIdRoute
  '/app/mock-tests/': typeof AppMockTestsIndexRoute
  '/app/results/': typeof AppResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/$': typeof AppSplatRoute
  '/app/admin': typeof AppAdminRoute
  '/app/current-affairs': typeof AppCurrentAffairsRoute
  '/app/review': typeof AppReviewRoute
  '/dev/math': typeof DevMathRoute
  '/app': typeof AppIndexRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/app/mock-test/$testId': typeof AppMockTestTestIdRoute
  '/app/results/$attemptId': typeof AppResultsAttemptIdRoute
  '/app/mock-tests': typeof AppMockTestsIndexRoute
  '/app/results': typeof AppResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$': typeof AppSplatRoute
  '/app/admin': typeof AppAdminRoute
  '/app/current-affairs': typeof AppCurrentAffairsRoute
  '/app/review': typeof AppReviewRoute
  '/dev/math': typeof DevMathRoute
  '/app/': typeof AppIndexRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/app/mock-test/$testId': typeof AppMockTestTestIdRoute
  '/app/results/$attemptId': typeof AppResultsAttemptIdRoute
  '/app/mock-tests/': typeof AppMockTestsIndexRoute
  '/app/results/': typeof AppResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/$'
    | '/app/admin'
    | '/app/current-affairs'
    | '/app/review'
    | '/dev/math'
    | '/app/'
    | '/api/voice/transcribe'
    | '/app/mock-test/$testId'
    | '/app/results/$attemptId'
    | '/app/mock-tests/'
    | '/app/results/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/$'
    | '/app/admin'
    | '/app/current-affairs'
    | '/app/review'
    | '/dev/math'
    | '/app'
    | '/api/voice/transcribe'
    | '/app/mock-test/$testId'
    | '/app/results/$attemptId'
    | '/app/mock-tests'
    | '/app/results'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/$'
    | '/app/admin'
    | '/app/current-affairs'
    | '/app/review'
    | '/dev/math'
    | '/app/'
    | '/api/voice/transcribe'
    | '/app/mock-test/$testId'
    | '/app/results/$attemptId'
    | '/app/mock-tests/'
    | '/app/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DevMathRoute: typeof DevMathRoute
  ApiVoiceTranscribeRoute: typeof ApiVoiceTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$': {
      id: '/app/$'
      path: '/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/current-affairs': {
      id: '/app/current-affairs'
      path: '/current-affairs'
      fullPath: '/app/current-affairs'
      preLoaderRoute: typeof AppCurrentAffairsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review': {
      id: '/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/dev/math': {
      id: '/dev/math'
      path: '/dev/math'
      fullPath: '/dev/math'
      preLoaderRoute: typeof DevMathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/transcribe': {
      id: '/api/voice/transcribe'
      path: '/api/voice/transcribe'
      fullPath: '/api/voice/transcribe'
      preLoaderRoute: typeof ApiVoiceTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/mock-test/$testId': {
      id: '/app/mock-test/$testId'
      path: '/mock-test/$testId'
      fullPath: '/app/mock-test/$testId'
      preLoaderRoute: typeof AppMockTestTestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mock-tests/': {
      id: '/app/mock-tests/'
      path: '/mock-tests'
      fullPath: '/app/mock-tests/'
      preLoaderRoute: typeof AppMockTestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/results/': {
      id: '/app/results/'
      path: '/results'
      fullPath: '/app/results/'
      preLoaderRoute: typeof AppResultsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/results/$attemptId': {
      id: '/app/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/app/results/$attemptId'
      preLoaderRoute: typeof AppResultsAttemptIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAdminRoute: typeof AppAdminRoute
  AppCurrentAffairsRoute: typeof AppCurrentAffairsRoute
  AppReviewRoute: typeof AppReviewRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMockTestTestIdRoute: typeof AppMockTestTestIdRoute
  AppResultsAttemptIdRoute: typeof AppResultsAttemptIdRoute
  AppMockTestsIndexRoute: typeof AppMockTestsIndexRoute
  AppResultsIndexRoute: typeof AppResultsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAdminRoute: AppAdminRoute,
  AppCurrentAffairsRoute: AppCurrentAffairsRoute,
  AppReviewRoute: AppReviewRoute,
  AppIndexRoute: AppIndexRoute,
  AppMockTestTestIdRoute: AppMockTestTestIdRoute,
  AppResultsAttemptIdRoute: AppResultsAttemptIdRoute,
  AppMockTestsIndexRoute: AppMockTestsIndexRoute,
  AppResultsIndexRoute: AppResultsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DevMathRoute: DevMathRoute,
  ApiVoiceTranscribeRoute: ApiVoiceTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
